"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class freeze_t(object):
    """ Message to freeze to NotIt """

    __slots__ = ["node_id"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.node_id = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(freeze_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.node_id))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != freeze_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return freeze_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = freeze_t()
        self.node_id = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if freeze_t in parents: return 0
        tmphash = (0x464d3db95f331c2c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if freeze_t._packed_fingerprint is None:
            freeze_t._packed_fingerprint = struct.pack(">Q", freeze_t._get_hash_recursive([]))
        return freeze_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", freeze_t._get_packed_fingerprint())[0]

