"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class position_t(object):
    """ Updates the position of the It and NotIt nodes """

    __slots__ = ["node_id", "x", "y", "is_it"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int8_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.node_id = 0
        """ LCM Type: int32_t """
        self.x = 0
        """
        node identifier
        LCM Type: int32_t
        """

        self.y = 0
        """
        x coord
        LCM Type: int32_t
        """

        self.is_it = 0
        """
        y coord
        LCM Type: int8_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(position_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iiib", self.node_id, self.x, self.y, self.is_it))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != position_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return position_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = position_t()
        self.node_id, self.x, self.y, self.is_it = struct.unpack(">iiib", buf.read(13))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if position_t in parents: return 0
        tmphash = (0x4f4f345ef50ceba6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if position_t._packed_fingerprint is None:
            position_t._packed_fingerprint = struct.pack(">Q", position_t._get_hash_recursive([]))
        return position_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", position_t._get_packed_fingerprint())[0]

