"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class sync_confirm_t(object):
    """ Synchronisation confirmation reply message  """

    __slots__ = ["ready"]

    __typenames__ = ["int8_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.ready = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(sync_confirm_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.ready))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sync_confirm_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sync_confirm_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = sync_confirm_t()
        self.ready = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if sync_confirm_t in parents: return 0
        tmphash = (0x4ca686a6fcdd853c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if sync_confirm_t._packed_fingerprint is None:
            sync_confirm_t._packed_fingerprint = struct.pack(">Q", sync_confirm_t._get_hash_recursive([]))
        return sync_confirm_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", sync_confirm_t._get_packed_fingerprint())[0]

